;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	coffee-newline-and-indent
	indent-for-tab-command
	org-delete-char
	orgtbl-hijacker-command-102
	orgtbl-self-insert-command
	reindent-then-newline-and-indent
	whole-line-or-region-kill-region
	whole-line-or-region-kill-ring-save
	whole-line-or-region-yank
	))

(setq mc/cmds-to-run-once
      '(
	coffee-dedent-line-backspace
	))
